import TopNav from '../components/navbar/TopNav'
import Providers from '../components/Providers'
import './globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'My Portfolio',
	description: 'Generated by Anton Krasilnikov',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<TopNav />
					<main className="container mx-auto">{children}</main>
				</Providers>
			</body>
		</html>
	)
}
